# Generated by Django 3.2.4 on 2021-06-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date_posted']},
        ),
    ]
